/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxf.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;
import com.wxf.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/WEB-INF/login.jsp" scope="request"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward ToLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	/*	LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		if(loginForm.getPassword().equals("123")){
			request.setAttribute("username", loginForm.getUsername());
			return mapping.findForward("loginok");
		}else {
//			return mapping.findForward("returnlogin");
			return mapping.findForward("error");
		}*/
		DynaActionForm userForm=(DynaActionForm) form;
		String username=(String) userForm.get("username");
		String password=userForm.get("password").toString();
		if(password.equals("123")){
			request.setAttribute("username",username);
			return mapping.findForward("loginok");
		}else {
//			return mapping.findForward("returnlogin");
			return mapping.findForward("error");
		}
	}
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward ReturnLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.getSession().invalidate();
		return mapping.findForward("error");
//		return mapping.findForward("returnlogin");
	}
}