/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxf.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.jndi.url.ldaps.ldapsURLContextFactory;
import com.wxf.dao.JdbcUtil;
import com.wxf.domain.User;
import com.wxf.service.UserService;
import com.wxf.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2016
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" scope="request"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		request.setAttribute("username", userForm.getUsername());
/*		if(userForm.getEmail().equals("123")){
			return mapping.findForward("ok");
		}else {
			return mapping.findForward("error");
		}
		*/
		UserService userService=new UserService();
		User user=new User();
		user.setUserid(userForm.getUserid());
		user.setUsername(userForm.getUsername());
		user.setPassword(userForm.getEmail());
		if(userService.register(user)){
			
			return mapping.findForward("ok");
		}else {
			return mapping.findForward("error");
		}
	}
		
}