/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wen.struts.action;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Arrays;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import sun.jdbc.odbc.OdbcDef;

import com.wen.struts.form.UserForm;
import com.wsf.domain.Users;
import com.wsf.service.UserService;
import com.wxf.util.MyUtils;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String flag="";
		UserForm userForm = (UserForm) form;
		FormFile formFile= userForm.getMyfile();
		String  oldFilename=formFile.getFileName();
		String  newFilename=MyUtils.GetNewFileName(oldFilename);
		int  filesize=formFile.getFileSize();
//		System.out.println(newFilename);
		String keepFilePath=this.getServlet().
				getServletContext().getRealPath("files");
		String filetype=formFile.getContentType();
//		System.out.println("文件类型为："+filetype);
//		System.out.println("文件路径为："+keepFilePath);
//		System.out.println("文件大小为："+filesize);
		/*if(filesize>1*1024*1024){
			request.setAttribute("size", "文件大于10M，请重新选择头像");
			mapping.findForward("return");
		}*/
		InputStream is=null;
		OutputStream os=null;
				try {
					is=formFile.getInputStream();
					os=new FileOutputStream(keepFilePath+"\\"+newFilename);
					int len=0;
					byte[] data=new byte[1024];
					while ((len=is.read(data))!=-1) {
						os.write(data, 0, len);
					}
					
					UserService userService=new UserService();
					Users user=new Users();
					user.setUsername(userForm.getUsername());
					user.setPassword(userForm.getPassword());
					user.setOldfilename(oldFilename);
					user.setNewfilename(newFilename);
					if(userService.AddUser(user)){
						return mapping.findForward("ok");
					}
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				
				} finally{
					try {
						os.close();
						is.close();
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
		
			return mapping.findForward("error");
	}
}