/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxf.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2016
 * 
 * XDoclet definition:
 * @struts.form name="questionForm"
 */
public class QuestionForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private  String qutitle;
	private  String qutype;
	private  String quscore;
	private  String quhard;
	private  String quAnswer;
	private  String examtype;
	private  Integer  id;
	private  String selectOption;
	public String getQutitle() {
		return qutitle;
	}
	public void setQutitle(String qutitle) {
		this.qutitle = qutitle;
	}
	public String getQutype() {
		return qutype;
	}
	public void setQutype(String qutype) {
		this.qutype = qutype;
	}
	public String getQuscore() {
		return quscore;
	}
	public void setQuscore(String quscore) {
		this.quscore = quscore;
	}
	public String getQuhard() {
		return quhard;
	}
	public void setQuhard(String quhard) {
		this.quhard = quhard;
	}
	public String getQuAnswer() {
		return quAnswer;
	}
	public void setQuAnswer(String quAnswer) {
		this.quAnswer = quAnswer;
	}
	public String getExamtype() {
		return examtype;
	}
	public void setExamtype(String examtype) {
		this.examtype = examtype;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getSelectOption() {
		return selectOption;
	}
	public void setSelectOption(String selectOption) {
		this.selectOption = selectOption;
	}
	
	
	
}