/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxf.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.sun.org.apache.bcel.internal.generic.NEW;
import com.wxf.dao.UserDao;
import com.wxf.dao.impl.UserDaoImpl;
import com.wxf.domain.User;
import com.wxf.exception.UserException;
import com.wxf.factory.BuildSessionFactory;
import com.wxf.factory.ServiceFactory;
import com.wxf.service.UserService;
import com.wxf.service.impl.UserServiceImpl;
import com.wxf.struts.form.UserLoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-08-2016
 * 
 * XDoclet definition:
 * @struts.action path="/loginAndOut" name="userLoginForm" parameter="flag" scope="request"
 * @struts.action-forward name="loginerr" path="/WEB-INF/userLogin.jsp"
 */
public class LoginAndOutAction extends DispatchAction {
	
	private UserService userService=null;
	public LoginAndOutAction(){
		userService=(UserService) ServiceFactory.getInstance(null).getService("userService");
	}
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserLoginForm userLoginForm = (UserLoginForm) form;// TODO Auto-generated method stub
		String username=userLoginForm.getUsername();
		String password=userLoginForm.getPassword();
		User user=new User();
		user=userService.validLogin(username, password);
		if(user!=null){
		return 	mapping.findForward("mainFrame");
		}else {
			return mapping.findForward("loginerr");
		}
	}
	
	public ActionForward ToReturn(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
			return mapping.findForward("mainFrame");
		}

}