/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxf.struts.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

import com.wxf.domain.Teacher;
import com.wxf.service.TeacherService;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2016
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ModifyPwdAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	@Resource
	private TeacherService teacherService;
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toCenter(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("toCenter");
	}
	
	
	public ActionForward toModifyPwd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("modifyPwd");
	}
	
	public ActionForward modifyPwd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
			DynaActionForm pwdForm=(DynaActionForm) form;
			String oldPwd=pwdForm.getString("oldPwd");
			String newPwd=pwdForm.getString("newPwd");
			String newPwdAgain=pwdForm.getString("newPwdAgain");
			System.out.println(oldPwd+","+newPwd);
			if(newPwdAgain.equals(newPwd)){
				try {
					Teacher loginTeacher=(Teacher) request.getSession().getAttribute("teacher");
					loginTeacher.setPassword(newPwd);
					teacherService.updateTeacher(loginTeacher);
					request.setAttribute("successMsg", "密码修改成功");
					return mapping.findForward("toCenter");
				} catch (Exception e) {
					// TODO: handle exception
					
				}
			}
			request.setAttribute("errorMsg", "密码修改失败，可能的原因是两次的密码输入不一致，请重新修改");
			return mapping.findForward("modifyPwd");
	}
}