/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wxf.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

import com.wxf.domain.Question;
import com.wxf.domain.Student;
import com.wxf.domain.Teacher;
import com.wxf.service.QuestionService;
import com.wxf.service.StudentService;
import com.wxf.service.TeacherService;

/** 
 * MyEclipse Struts
 * Creation date: 07-18-2016
 * 
 * XDoclet definition:
 * @struts.action path="/show" name="showForm" parameter="flag" scope="request"
 */
public class ShowAction extends DispatchAction {
	@Resource
	private StudentService studentService;
	@Resource
	private TeacherService teacherService;
	@Resource
	private  QuestionService questionService;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showStu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm pageSizeForm=(DynaActionForm) form;
		String pageSizeStr=pageSizeForm.getString("size");
		String ps=request.getParameter("pageSize");
		int pageSize=4;
		if(ps==null){
			pageSize=4;
		}else {
			pageSize=Integer.parseInt(ps);
		}
		
		try {
			if(pageSizeStr!=null && !pageSizeStr.equals("")){
				pageSize=Integer.parseInt(pageSizeStr);
			}
		} catch (Exception e) {
			// TODO: handle exception
			pageSize=Integer.parseInt(request.getParameter("pageSize").toString());
		}
		int pageNow=1;
		String pageNowStr=request.getParameter("pageNow");
		int pageCount=studentService.getStudentCounts(pageSize);
		if(pageNowStr!=null && !pageNowStr.equals("")){
			pageNow=Integer.parseInt(pageNowStr);
		}
		if(pageNow>pageCount){
			pageNow=pageCount;
		}
		List<Student> list=studentService.findStudentsWithPage(pageSize, pageNow);
		request.setAttribute("studentList",list);
		request.setAttribute("studentCounts", pageCount);
		request.setAttribute("pageNo", pageNow);
		request.setAttribute("pageSize", pageSize);
		return mapping.findForward("toShowStu");
	}
	
	
	public ActionForward showQuestion(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm pageSizeForm=(DynaActionForm) form;
		String pageSizeStr=pageSizeForm.getString("size");
		String ps=request.getParameter("pageSize");
		int pageSize=4;
		if(ps==null){
			pageSize=4;
		}else {
			pageSize=Integer.parseInt(ps);
		}
		
		try {
			if(pageSizeStr!=null && !pageSizeStr.equals("")){
				pageSize=Integer.parseInt(pageSizeStr);
			}
		} catch (Exception e) {
			// TODO: handle exception
			pageSize=Integer.parseInt(request.getParameter("pageSize").toString());
		}
		int pageNow=1;
		String pageNowStr=request.getParameter("pageNow");
		int pageCount=questionService.getQuestionCounts(pageSize);
		if(pageNowStr!=null && !pageNowStr.equals("")){
			pageNow=Integer.parseInt(pageNowStr);
		}
		if(pageNow>pageCount){
			pageNow=pageCount;
		}
		List<Question> list=questionService.findWithPage(pageSize, pageNow);
		request.setAttribute("questions",list);
		request.setAttribute("questionCounts", pageCount);
		request.setAttribute("pageNo", pageNow);
		request.setAttribute("pageSize", pageSize);
		return mapping.findForward("showQuestion");
		/*List<Question> list=questionService.findWithPage(7, 1);
		request.setAttribute("questions", list);
		System.out.println(list.size());
		return mapping.findForward("showQuestion");*/
	}
}